In [1]:
%pylab inline

import numpy as np
import matplotlib as plt
import pandas as pd
import math

Populating the interactive namespace from numpy and matplotlib

In [21]:
nba = pd.read_csv(open('Data/nba_2013.csv', 'r'))
nba2 = pd.DataFrame.from_csv(open('Data/nba_2013.csv'))
#They yield slightly different DataFrames! read_csv adds a numbered index, from_csv uses first column as index.

In [19]:
nba.head()

,player,pos,age,bref_team_id,g,gs,mp,fg,fga,fg.,...,drb,trb,ast,stl,blk,tov,pf,pts,season,season_end
0,Quincy Acy,SF,23,TOT,63,0,847,66,141,0.468,...,144,216,28,23,26,30,122,171,2013-2014,2013
1,Steven Adams,C,20,OKC,81,20,1197,93,185,0.503,...,190,332,43,40,57,71,203,265,2013-2014,2013
2,Jeff Adrien,PF,27,TOT,53,12,961,143,275,0.520,...,204,306,38,24,36,39,108,362,2013-2014,2013
3,Arron Afflalo,SG,28,ORL,73,73,2552,464,1011,0.459,...,230,262,248,35,3,146,136,1330,2013-2014,2013
4,Alexis Ajinca,C,25,NOP,56,30,951,136,249,0.546,...,183,277,40,23,46,63,187,328,2013-2014,2013

In [20]:
nba2.head()

,pos,age,bref_team_id,g,gs,mp,fg,fga,fg.,x3p,...,drb,trb,ast,stl,blk,tov,pf,pts,season,season_end
player,,,,,,,,,,,,,,,,,,,,,
Quincy Acy,SF,23,TOT,63,0,847,66,141,0.468,4,...,144,216,28,23,26,30,122,171,2013-2014,2013
Steven Adams,C,20,OKC,81,20,1197,93,185,0.503,0,...,190,332,43,40,57,71,203,265,2013-2014,2013
Jeff Adrien,PF,27,TOT,53,12,961,143,275,0.520,0,...,204,306,38,24,36,39,108,362,2013-2014,2013
Arron Afflalo,SG,28,ORL,73,73,2552,464,1011,0.459,128,...,230,262,248,35,3,146,136,1330,2013-2014,2013
Alexis Ajinca,C,25,NOP,56,30,951,136,249,0.546,0,...,183,277,40,23,46,63,187,328,2013-2014,2013

In [24]:
nba.columns.values

array(['player', 'pos', 'age', 'bref_team_id', 'g', 'gs', 'mp', 'fg',
       'fga', 'fg.', 'x3p', 'x3pa', 'x3p.', 'x2p', 'x2pa', 'x2p.', 'efg.',
       'ft', 'fta', 'ft.', 'orb', 'drb', 'trb', 'ast', 'stl', 'blk', 'tov',
       'pf', 'pts', 'season', 'season_end'], dtype=object)

In [38]:
def euclidean_distance(row):
    """
    A simple euclidean distance function
    """
    inner_value = 0
    for k in distance_columns:
        inner_value += (row[k] - selected_player[k]) ** 2
    return math.sqrt(inner_value)

In [31]:
position = nba['pos'].value_counts()
position

SG    109
SF     99
PF     96
C      90
PG     85
F       1
G       1
dtype: int64

In [37]:
selected_player = nba[nba["player"] == "LeBron James"].iloc[0]
lebron_distance = nba.apply(euclidean_distance, axis=1)
print lebron_distance

NameError: ("global name 'distance_columns' is not defined", u'occurred at index 0')

In [ ]:
lebron_distance = nba.apply(euclidean_distance, player))